"use client"

import React, { createContext, useContext, useEffect, useMemo, useState } from "react"

export type AppLanguage =
  | "en"
  | "zh"
  | "ja"
  | "ru"
  | "fr"
  | "pt"
  | "es"
  | "de"
  | "tr"
  | "ar"
  | "ur"
  | "pcm"
  | "hi"
  | "id"
  | "ms"
  | "bn"
  | "vi"
  | "fa"
  | "ko"
  | "it"

export const SUPPORTED_LANGUAGES: Array<{ code: AppLanguage; label: string; native: string; flag: string }> = [
  { code: "en", label: "English", native: "English", flag: "🇬🇧" },
]

type Dict = Record<string, string>

const dictionaries: Record<AppLanguage, Dict> = {
  en: {
    home: "Home",
    friends: "Friends",
    wallet: "Wallet",
    skillBasedGame: "Skill based game",
    playNow: "Play Now",
    vsAI: "vs AI",
    oneVOne: "1v1",
    loading: "Loading...",
    tapBackAgainExit: "Tap back again to exit the game",
    languages: "Languages",
    gameSettings: "Game Settings",
    guideLine: "Guide Line",
    guideLineDesc: "Aim helper line while shooting",
    sound: "Sound",
    soundDesc: "Enable in-game sounds",
    gameTutorial: "Game Tutorial",
    gameTutorialDesc: "Learn shots, cue control and match flow",
    learn: "Learn",
    aiDifficulty: "AI Difficulty",
    noUsername: "No username",
    level: "Level",
  },
  zh: { home: "首页", friends: "好友", wallet: "钱包", skillBasedGame: "技巧竞技", playNow: "立即开始", vsAI: "对战AI", oneVOne: "1v1", loading: "加载中...", tapBackAgainExit: "再次返回以退出游戏", languages: "语言", gameSettings: "游戏设置", guideLine: "辅助线", guideLineDesc: "击球时显示瞄准辅助", sound: "声音", soundDesc: "启用游戏音效", gameTutorial: "游戏教程", gameTutorialDesc: "学习击球、球杆控制和流程", learn: "学习", aiDifficulty: "AI难度", noUsername: "无用户名", level: "等级" },
  ja: { home: "ホーム", friends: "友だち", wallet: "ウォレット", skillBasedGame: "スキルベースのゲーム", playNow: "今すぐプレイ", vsAI: "AI対戦", oneVOne: "1v1", loading: "読み込み中...", tapBackAgainExit: "もう一度戻るでゲーム終了", languages: "言語", gameSettings: "ゲーム設定", guideLine: "ガイドライン", guideLineDesc: "ショット時の照準補助", sound: "サウンド", soundDesc: "ゲーム音を有効化", gameTutorial: "ゲームチュートリアル", gameTutorialDesc: "ショットと操作を学ぶ", learn: "学ぶ", aiDifficulty: "AI難易度", noUsername: "ユーザー名なし", level: "レベル" },
  ru: { home: "Главная", friends: "Друзья", wallet: "Кошелёк", skillBasedGame: "Игра навыка", playNow: "Играть", vsAI: "против ИИ", oneVOne: "1 на 1", loading: "Загрузка...", tapBackAgainExit: "Нажмите назад ещё раз для выхода", languages: "Языки", gameSettings: "Настройки игры", guideLine: "Линия прицеливания", guideLineDesc: "Подсказка при прицеливании", sound: "Звук", soundDesc: "Включить звук", gameTutorial: "Обучение", gameTutorialDesc: "Изучите удары и управление", learn: "Изучить", aiDifficulty: "Сложность ИИ", noUsername: "Без имени", level: "Уровень" },
  fr: { home: "Accueil", friends: "Amis", wallet: "Portefeuille", skillBasedGame: "Jeu d’adresse", playNow: "Jouer", vsAI: "vs IA", oneVOne: "1v1", loading: "Chargement...", tapBackAgainExit: "Appuyez encore pour quitter", languages: "Langues", gameSettings: "Paramètres du jeu", guideLine: "Ligne guide", guideLineDesc: "Aide à la visée", sound: "Son", soundDesc: "Activer le son", gameTutorial: "Tutoriel", gameTutorialDesc: "Apprenez les coups et contrôles", learn: "Apprendre", aiDifficulty: "Difficulté IA", noUsername: "Pas de pseudo", level: "Niveau" },
  pt: { home: "Início", friends: "Amigos", wallet: "Carteira", skillBasedGame: "Jogo de habilidade", playNow: "Jogar", vsAI: "vs IA", oneVOne: "1v1", loading: "Carregando...", tapBackAgainExit: "Toque voltar novamente para sair", languages: "Idiomas", gameSettings: "Configurações", guideLine: "Linha guia", guideLineDesc: "Ajuda na mira", sound: "Som", soundDesc: "Ativar som", gameTutorial: "Tutorial", gameTutorialDesc: "Aprenda jogadas e controle", learn: "Aprender", aiDifficulty: "Dificuldade IA", noUsername: "Sem nome", level: "Nível" },
  es: { home: "Inicio", friends: "Amigos", wallet: "Billetera", skillBasedGame: "Juego de habilidad", playNow: "Jugar", vsAI: "vs IA", oneVOne: "1v1", loading: "Cargando...", tapBackAgainExit: "Toca atrás otra vez para salir", languages: "Idiomas", gameSettings: "Ajustes del juego", guideLine: "Línea guía", guideLineDesc: "Ayuda de puntería", sound: "Sonido", soundDesc: "Activar sonido", gameTutorial: "Tutorial", gameTutorialDesc: "Aprende golpes y control", learn: "Aprender", aiDifficulty: "Dificultad IA", noUsername: "Sin usuario", level: "Nivel" },
  de: { home: "Start", friends: "Freunde", wallet: "Wallet", skillBasedGame: "Geschicklichkeitsspiel", playNow: "Spielen", vsAI: "gegen KI", oneVOne: "1v1", loading: "Laden...", tapBackAgainExit: "Erneut zurück tippen zum Beenden", languages: "Sprachen", gameSettings: "Spieleinstellungen", guideLine: "Hilfslinie", guideLineDesc: "Zielhilfe", sound: "Ton", soundDesc: "Ton aktivieren", gameTutorial: "Tutorial", gameTutorialDesc: "Schläge und Steuerung lernen", learn: "Lernen", aiDifficulty: "KI-Schwierigkeit", noUsername: "Kein Benutzername", level: "Level" },
  tr: { home: "Ana Sayfa", friends: "Arkadaşlar", wallet: "Cüzdan", skillBasedGame: "Yetenek oyunu", playNow: "Oyna", vsAI: "Yapay Zeka", oneVOne: "1v1", loading: "Yükleniyor...", tapBackAgainExit: "Çıkmak için tekrar geri dokun", languages: "Diller", gameSettings: "Oyun Ayarları", guideLine: "Kılavuz Çizgi", guideLineDesc: "Nişan yardımı", sound: "Ses", soundDesc: "Oyun sesleri", gameTutorial: "Eğitim", gameTutorialDesc: "Atış ve kontrolü öğren", learn: "Öğren", aiDifficulty: "YZ Zorluğu", noUsername: "Kullanıcı adı yok", level: "Seviye" },
  ar: { home: "الرئيسية", friends: "الأصدقاء", wallet: "المحفظة", skillBasedGame: "لعبة مهارة", playNow: "ابدأ اللعب", vsAI: "ضد الذكاء", oneVOne: "1v1", loading: "جارٍ التحميل...", tapBackAgainExit: "اضغط رجوع مرة أخرى للخروج", languages: "اللغات", gameSettings: "إعدادات اللعبة", guideLine: "خط المساعدة", guideLineDesc: "مساعدة التصويب", sound: "الصوت", soundDesc: "تفعيل الصوت", gameTutorial: "تعليم اللعبة", gameTutorialDesc: "تعلّم التسديد والتحكم", learn: "تعلّم", aiDifficulty: "صعوبة الذكاء", noUsername: "لا يوجد اسم", level: "المستوى" },
  ur: { home: "ہوم", friends: "دوست", wallet: "والیٹ", skillBasedGame: "مہارت پر مبنی کھیل", playNow: "ابھی کھیلیں", vsAI: "AI کے خلاف", oneVOne: "1v1", loading: "لوڈ ہو رہا ہے...", tapBackAgainExit: "باہر نکلنے کیلئے دوبارہ بیک دبائیں", languages: "زبانیں", gameSettings: "گیم سیٹنگز", guideLine: "گائیڈ لائن", guideLineDesc: "نشانہ لگانے میں مدد", sound: "آواز", soundDesc: "گیم آواز فعال کریں", gameTutorial: "گیم ٹیوٹوریل", gameTutorialDesc: "شاٹس اور کنٹرول سیکھیں", learn: "سیکھیں", aiDifficulty: "AI مشکل", noUsername: "یوزرنیم نہیں", level: "لیول" },
  pcm: { home: "Home", friends: "Padi dem", wallet: "Wallet", skillBasedGame: "Skill game", playNow: "Play now", vsAI: "vs AI", oneVOne: "1v1", loading: "Dey load...", tapBackAgainExit: "Tap back again make you comot game", languages: "Language", gameSettings: "Game settings", guideLine: "Guide line", guideLineDesc: "Aim helper line", sound: "Sound", soundDesc: "Turn game sound on", gameTutorial: "Game tutorial", gameTutorialDesc: "Learn shot and control", learn: "Learn", aiDifficulty: "AI level", noUsername: "No username", level: "Level" },
  hi: { home: "होम", friends: "दोस्त", wallet: "वॉलेट", skillBasedGame: "कौशल आधारित खेल", playNow: "अभी खेलें", vsAI: "AI के साथ", oneVOne: "1v1", loading: "लोड हो रहा है...", tapBackAgainExit: "बाहर निकलने के लिए फिर से बैक दबाएँ", languages: "भाषाएँ", gameSettings: "गेम सेटिंग्स", guideLine: "गाइड लाइन", guideLineDesc: "निशाना सहायता", sound: "साउंड", soundDesc: "गेम साउंड चालू करें", gameTutorial: "गेम ट्यूटोरियल", gameTutorialDesc: "शॉट और कंट्रोल सीखें", learn: "सीखें", aiDifficulty: "AI कठिनाई", noUsername: "यूज़रनेम नहीं", level: "लेवल" },
  id: { home: "Beranda", friends: "Teman", wallet: "Dompet", skillBasedGame: "Game berbasis skill", playNow: "Main", vsAI: "vs AI", oneVOne: "1v1", loading: "Memuat...", tapBackAgainExit: "Tekan kembali lagi untuk keluar", languages: "Bahasa", gameSettings: "Pengaturan Game", guideLine: "Garis Pandu", guideLineDesc: "Bantuan bidik", sound: "Suara", soundDesc: "Aktifkan suara", gameTutorial: "Tutorial", gameTutorialDesc: "Pelajari pukulan & kontrol", learn: "Pelajari", aiDifficulty: "Kesulitan AI", noUsername: "Tanpa username", level: "Level" },
  ms: { home: "Utama", friends: "Rakan", wallet: "Dompet", skillBasedGame: "Permainan kemahiran", playNow: "Main", vsAI: "lwn AI", oneVOne: "1v1", loading: "Memuat...", tapBackAgainExit: "Tekan kembali sekali lagi untuk keluar", languages: "Bahasa", gameSettings: "Tetapan Permainan", guideLine: "Garis Panduan", guideLineDesc: "Bantuan sasaran", sound: "Bunyi", soundDesc: "Aktifkan bunyi", gameTutorial: "Tutorial", gameTutorialDesc: "Belajar pukulan & kawalan", learn: "Belajar", aiDifficulty: "Kesukaran AI", noUsername: "Tiada nama", level: "Tahap" },
  bn: { home: "হোম", friends: "বন্ধুরা", wallet: "ওয়ালেট", skillBasedGame: "দক্ষতার খেলা", playNow: "খেলুন", vsAI: "AI বনাম", oneVOne: "1v1", loading: "লোড হচ্ছে...", tapBackAgainExit: "বের হতে আবার ব্যাক চাপুন", languages: "ভাষাসমূহ", gameSettings: "গেম সেটিংস", guideLine: "গাইড লাইন", guideLineDesc: "লক্ষ্য সহায়তা", sound: "সাউন্ড", soundDesc: "গেম সাউন্ড চালু", gameTutorial: "টিউটোরিয়াল", gameTutorialDesc: "শট ও নিয়ন্ত্রণ শিখুন", learn: "শিখুন", aiDifficulty: "AI কঠিনতা", noUsername: "ইউজারনেম নেই", level: "লেভেল" },
  vi: { home: "Trang chủ", friends: "Bạn bè", wallet: "Ví", skillBasedGame: "Trò chơi kỹ năng", playNow: "Chơi ngay", vsAI: "đấu AI", oneVOne: "1v1", loading: "Đang tải...", tapBackAgainExit: "Chạm quay lại lần nữa để thoát", languages: "Ngôn ngữ", gameSettings: "Cài đặt game", guideLine: "Đường ngắm", guideLineDesc: "Hỗ trợ ngắm bắn", sound: "Âm thanh", soundDesc: "Bật âm thanh", gameTutorial: "Hướng dẫn", gameTutorialDesc: "Học cách bắn và điều khiển", learn: "Học", aiDifficulty: "Độ khó AI", noUsername: "Không có tên", level: "Cấp độ" },
  fa: { home: "خانه", friends: "دوستان", wallet: "کیف پول", skillBasedGame: "بازی مهارتی", playNow: "شروع بازی", vsAI: "مقابل هوش مصنوعی", oneVOne: "1v1", loading: "در حال بارگذاری...", tapBackAgainExit: "برای خروج دوباره بازگشت را بزنید", languages: "زبان‌ها", gameSettings: "تنظیمات بازی", guideLine: "خط راهنما", guideLineDesc: "کمک به نشانه‌گیری", sound: "صدا", soundDesc: "فعال‌سازی صدا", gameTutorial: "آموزش بازی", gameTutorialDesc: "یادگیری ضربه و کنترل", learn: "یادگیری", aiDifficulty: "سختی هوش مصنوعی", noUsername: "بدون نام کاربری", level: "سطح" },
  ko: { home: "홈", friends: "친구", wallet: "지갑", skillBasedGame: "실력 기반 게임", playNow: "바로 플레이", vsAI: "AI 대전", oneVOne: "1v1", loading: "로딩 중...", tapBackAgainExit: "게임을 종료하려면 뒤로를 다시 누르세요", languages: "언어", gameSettings: "게임 설정", guideLine: "가이드 라인", guideLineDesc: "조준 보조선", sound: "사운드", soundDesc: "게임 사운드", gameTutorial: "게임 튜토리얼", gameTutorialDesc: "샷과 컨트롤 학습", learn: "학습", aiDifficulty: "AI 난이도", noUsername: "사용자 이름 없음", level: "레벨" },
  it: { home: "Home", friends: "Amici", wallet: "Portafoglio", skillBasedGame: "Gioco di abilità", playNow: "Gioca ora", vsAI: "vs IA", oneVOne: "1v1", loading: "Caricamento...", tapBackAgainExit: "Tocca indietro di nuovo per uscire", languages: "Lingue", gameSettings: "Impostazioni gioco", guideLine: "Linea guida", guideLineDesc: "Aiuto alla mira", sound: "Audio", soundDesc: "Abilita audio", gameTutorial: "Tutorial", gameTutorialDesc: "Impara tiri e controllo", learn: "Impara", aiDifficulty: "Difficoltà IA", noUsername: "Nessun username", level: "Livello" },
}

const pageDictionaries: Partial<Record<AppLanguage, Dict>> = {
  en: { walletLoadFailed: "Failed to load wallet data", enterUsdtAddress: "Please enter your USDT wallet address", enterValidAmount: "Please enter a valid amount", minimumWithdrawalIs: "Minimum withdrawal is", insufficientMetalBalance: "Insufficient Metal balance", withdrawalSubmitted: "Withdrawal request submitted!", withdrawalSubmitFailed: "Failed to submit withdrawal", pending: "Pending", approved: "Approved", completed: "Completed", rejected: "Rejected", withdrawMetalTokens: "Withdraw your Metal tokens", metalBalance: "Metal Balance", estimatedProcessing: "Estimated Processing", withdrawToUsdt: "Withdraw to USDT", usdtWalletAddress: "USDT Wallet Address (TRC-20)", enterUsdtAddressShort: "Enter your USDT address", amountMetal: "Amount (Metal)", min: "Min", withdrawalFeeNotice: "A fee of", willBeDeducted: "will be deducted.", requestWithdrawal: "Request Withdrawal", withdrawalHistory: "Withdrawal History", noWithdrawalsYet: "No withdrawals yet", copied: "Copied!", copyFailed: "Failed to copy", joinAndEarn: "Join", andEarnMetalTokens: "and earn Metal tokens!", inviteFriends: "Invite Friends", earnPerFriendInvite: "Earn Metal tokens for every friend you invite", friendsInvited: "Friends Invited", metalEarned: "Metal Earned", metalPerFriend: "Metal per friend", commission: "commission", inviteAFriend: "Invite a Friend", linkCopied: "Link Copied!", copyInviteLink: "Copy Invite Link", yourFriends: "Your Friends", noFriendsInvitedYet: "No friends invited yet", shareLinkToStartEarning: "Share your link to start earning!", user: "User", joined: "Joined" },
  zh: { walletLoadFailed: "加载钱包数据失败", enterUsdtAddress: "请输入您的USDT钱包地址", enterValidAmount: "请输入有效金额", minimumWithdrawalIs: "最低提现为", insufficientMetalBalance: "Metal余额不足", withdrawalSubmitted: "提现申请已提交！", withdrawalSubmitFailed: "提交提现失败", pending: "处理中", approved: "已通过", completed: "已完成", rejected: "已拒绝", withdrawMetalTokens: "提取您的Metal代币", metalBalance: "Metal余额", estimatedProcessing: "预计处理时间", withdrawToUsdt: "提现到USDT", usdtWalletAddress: "USDT钱包地址 (TRC-20)", enterUsdtAddressShort: "输入您的USDT地址", amountMetal: "数量 (Metal)", min: "最小", withdrawalFeeNotice: "手续费", willBeDeducted: "将被扣除。", requestWithdrawal: "申请提现", withdrawalHistory: "提现记录", noWithdrawalsYet: "暂无提现", copied: "已复制！", copyFailed: "复制失败", joinAndEarn: "加入", andEarnMetalTokens: "并赚取Metal代币！", inviteFriends: "邀请好友", earnPerFriendInvite: "每邀请一位好友即可赚取Metal", friendsInvited: "已邀请好友", metalEarned: "已赚取Metal", metalPerFriend: "每位好友Metal", commission: "佣金", inviteAFriend: "邀请好友", linkCopied: "链接已复制！", copyInviteLink: "复制邀请链接", yourFriends: "你的好友", noFriendsInvitedYet: "还没有邀请好友", shareLinkToStartEarning: "分享链接开始赚取！", user: "用户", joined: "加入于" },
  ja: { walletLoadFailed: "ウォレットデータの読み込みに失敗しました", enterUsdtAddress: "USDTウォレットアドレスを入力してください", enterValidAmount: "有効な金額を入力してください", minimumWithdrawalIs: "最小出金額は", insufficientMetalBalance: "Metal残高が不足しています", withdrawalSubmitted: "出金リクエストを送信しました！", withdrawalSubmitFailed: "出金リクエストの送信に失敗しました", pending: "保留中", approved: "承認済み", completed: "完了", rejected: "拒否", withdrawMetalTokens: "Metalトークンを出金", metalBalance: "Metal残高", estimatedProcessing: "処理予定時間", withdrawToUsdt: "USDTへ出金", usdtWalletAddress: "USDTウォレットアドレス (TRC-20)", enterUsdtAddressShort: "USDTアドレスを入力", amountMetal: "金額 (Metal)", min: "最小", withdrawalFeeNotice: "手数料", willBeDeducted: "が差し引かれます。", requestWithdrawal: "出金を申請", withdrawalHistory: "出金履歴", noWithdrawalsYet: "出金履歴はありません", copied: "コピーしました！", copyFailed: "コピーに失敗しました", joinAndEarn: "参加して", andEarnMetalTokens: "Metalトークンを獲得！", inviteFriends: "友だちを招待", earnPerFriendInvite: "友だちを招待するたびにMetalを獲得", friendsInvited: "招待した友だち", metalEarned: "獲得したMetal", metalPerFriend: "友だち1人あたりのMetal", commission: "コミッション", inviteAFriend: "友だちを招待", linkCopied: "リンクをコピーしました！", copyInviteLink: "招待リンクをコピー", yourFriends: "あなたの友だち", noFriendsInvitedYet: "まだ友だちを招待していません", shareLinkToStartEarning: "リンクを共有して獲得開始！", user: "ユーザー", joined: "参加日" },
  ko: { walletLoadFailed: "지갑 데이터를 불러오지 못했습니다", enterUsdtAddress: "USDT 지갑 주소를 입력하세요", enterValidAmount: "유효한 금액을 입력하세요", minimumWithdrawalIs: "최소 출금 금액은", insufficientMetalBalance: "Metal 잔액이 부족합니다", withdrawalSubmitted: "출금 요청이 제출되었습니다!", withdrawalSubmitFailed: "출금 요청 제출 실패", pending: "대기 중", approved: "승인됨", completed: "완료", rejected: "거절됨", withdrawMetalTokens: "Metal 토큰 출금", metalBalance: "Metal 잔액", estimatedProcessing: "예상 처리 시간", withdrawToUsdt: "USDT로 출금", usdtWalletAddress: "USDT 지갑 주소 (TRC-20)", enterUsdtAddressShort: "USDT 주소 입력", amountMetal: "금액 (Metal)", min: "최소", withdrawalFeeNotice: "수수료", willBeDeducted: "가 차감됩니다.", requestWithdrawal: "출금 요청", withdrawalHistory: "출금 내역", noWithdrawalsYet: "출금 내역이 없습니다", copied: "복사됨!", copyFailed: "복사 실패", joinAndEarn: "참여하고", andEarnMetalTokens: "Metal 토큰을 획득하세요!", inviteFriends: "친구 초대", earnPerFriendInvite: "친구를 초대할 때마다 Metal 획득", friendsInvited: "초대한 친구", metalEarned: "획득한 Metal", metalPerFriend: "친구당 Metal", commission: "커미션", inviteAFriend: "친구 초대", linkCopied: "링크 복사 완료!", copyInviteLink: "초대 링크 복사", yourFriends: "내 친구", noFriendsInvitedYet: "아직 초대한 친구가 없습니다", shareLinkToStartEarning: "링크를 공유하고 보상 받기 시작하세요!", user: "사용자", joined: "가입일" },
  ru: { walletLoadFailed: "Не удалось загрузить данные кошелька", enterUsdtAddress: "Введите адрес вашего USDT-кошелька", enterValidAmount: "Введите корректную сумму", minimumWithdrawalIs: "Минимальный вывод", insufficientMetalBalance: "Недостаточно Metal", withdrawalSubmitted: "Заявка на вывод отправлена!", withdrawalSubmitFailed: "Не удалось отправить заявку на вывод", pending: "Ожидается", approved: "Одобрено", completed: "Завершено", rejected: "Отклонено", withdrawMetalTokens: "Вывод ваших Metal токенов", metalBalance: "Баланс Metal", estimatedProcessing: "Ожидаемое время обработки", withdrawToUsdt: "Вывести в USDT", usdtWalletAddress: "Адрес USDT кошелька (TRC-20)", enterUsdtAddressShort: "Введите адрес USDT", amountMetal: "Сумма (Metal)", min: "Мин", withdrawalFeeNotice: "Комиссия", willBeDeducted: "будет удержана.", requestWithdrawal: "Запросить вывод", withdrawalHistory: "История выводов", noWithdrawalsYet: "Выводов пока нет", copied: "Скопировано!", copyFailed: "Не удалось скопировать", joinAndEarn: "Присоединяйся к", andEarnMetalTokens: "и зарабатывай Metal токены!", inviteFriends: "Пригласи друзей", earnPerFriendInvite: "Зарабатывай Metal за каждого приглашённого друга", friendsInvited: "Приглашено друзей", metalEarned: "Заработано Metal", metalPerFriend: "Metal за друга", commission: "комиссия", inviteAFriend: "Пригласить друга", linkCopied: "Ссылка скопирована!", copyInviteLink: "Скопировать ссылку", yourFriends: "Ваши друзья", noFriendsInvitedYet: "Вы ещё никого не пригласили", shareLinkToStartEarning: "Поделитесь ссылкой и начните зарабатывать!", user: "Пользователь", joined: "Присоединился" },
  fr: { walletLoadFailed: "Échec du chargement du portefeuille", enterUsdtAddress: "Veuillez saisir votre adresse USDT", enterValidAmount: "Veuillez saisir un montant valide", minimumWithdrawalIs: "Le retrait minimum est", insufficientMetalBalance: "Solde Metal insuffisant", withdrawalSubmitted: "Demande de retrait envoyée !", withdrawalSubmitFailed: "Échec de l’envoi du retrait", pending: "En attente", approved: "Approuvé", completed: "Terminé", rejected: "Rejeté", withdrawMetalTokens: "Retirez vos tokens Metal", metalBalance: "Solde Metal", estimatedProcessing: "Traitement estimé", withdrawToUsdt: "Retirer vers USDT", usdtWalletAddress: "Adresse USDT (TRC-20)", enterUsdtAddressShort: "Entrez votre adresse USDT", amountMetal: "Montant (Metal)", min: "Min", withdrawalFeeNotice: "Des frais de", willBeDeducted: "seront déduits.", requestWithdrawal: "Demander un retrait", withdrawalHistory: "Historique des retraits", noWithdrawalsYet: "Aucun retrait pour le moment", copied: "Copié !", copyFailed: "Échec de la copie", joinAndEarn: "Rejoignez", andEarnMetalTokens: "et gagnez des tokens Metal !", inviteFriends: "Inviter des amis", earnPerFriendInvite: "Gagnez des Metal pour chaque ami invité", friendsInvited: "Amis invités", metalEarned: "Metal gagnés", metalPerFriend: "Metal par ami", commission: "commission", inviteAFriend: "Inviter un ami", linkCopied: "Lien copié !", copyInviteLink: "Copier le lien d’invitation", yourFriends: "Vos amis", noFriendsInvitedYet: "Aucun ami invité", shareLinkToStartEarning: "Partagez votre lien pour commencer à gagner !", user: "Utilisateur", joined: "Inscrit" },
  es: { walletLoadFailed: "Error al cargar la billetera", enterUsdtAddress: "Ingrese su dirección USDT", enterValidAmount: "Ingrese un monto válido", minimumWithdrawalIs: "El retiro mínimo es", insufficientMetalBalance: "Saldo Metal insuficiente", withdrawalSubmitted: "¡Solicitud de retiro enviada!", withdrawalSubmitFailed: "No se pudo enviar el retiro", pending: "Pendiente", approved: "Aprobado", completed: "Completado", rejected: "Rechazado", withdrawMetalTokens: "Retira tus tokens Metal", metalBalance: "Saldo Metal", estimatedProcessing: "Procesamiento estimado", withdrawToUsdt: "Retirar a USDT", usdtWalletAddress: "Dirección USDT (TRC-20)", enterUsdtAddressShort: "Ingresa tu dirección USDT", amountMetal: "Cantidad (Metal)", min: "Mín", withdrawalFeeNotice: "Una tarifa de", willBeDeducted: "será descontada.", requestWithdrawal: "Solicitar retiro", withdrawalHistory: "Historial de retiros", noWithdrawalsYet: "Aún no hay retiros", copied: "¡Copiado!", copyFailed: "Error al copiar", joinAndEarn: "Únete a", andEarnMetalTokens: "¡y gana tokens Metal!", inviteFriends: "Invita amigos", earnPerFriendInvite: "Gana Metal por cada amigo invitado", friendsInvited: "Amigos invitados", metalEarned: "Metal ganado", metalPerFriend: "Metal por amigo", commission: "comisión", inviteAFriend: "Invitar a un amigo", linkCopied: "¡Enlace copiado!", copyInviteLink: "Copiar enlace", yourFriends: "Tus amigos", noFriendsInvitedYet: "Aún no invitaste amigos", shareLinkToStartEarning: "¡Comparte tu enlace para empezar a ganar!", user: "Usuario", joined: "Se unió" },
  de: { walletLoadFailed: "Wallet-Daten konnten nicht geladen werden", enterUsdtAddress: "Bitte gib deine USDT-Wallet-Adresse ein", enterValidAmount: "Bitte gib einen gültigen Betrag ein", minimumWithdrawalIs: "Mindestabhebung ist", insufficientMetalBalance: "Nicht genügend Metal", withdrawalSubmitted: "Auszahlungsanfrage gesendet!", withdrawalSubmitFailed: "Auszahlungsanfrage fehlgeschlagen", pending: "Ausstehend", approved: "Genehmigt", completed: "Abgeschlossen", rejected: "Abgelehnt", withdrawMetalTokens: "Ziehe deine Metal-Token ab", metalBalance: "Metal-Guthaben", estimatedProcessing: "Geschätzte Bearbeitung", withdrawToUsdt: "Zu USDT auszahlen", usdtWalletAddress: "USDT-Wallet-Adresse (TRC-20)", enterUsdtAddressShort: "USDT-Adresse eingeben", amountMetal: "Betrag (Metal)", min: "Min", withdrawalFeeNotice: "Eine Gebühr von", willBeDeducted: "wird abgezogen.", requestWithdrawal: "Auszahlung anfordern", withdrawalHistory: "Auszahlungsverlauf", noWithdrawalsYet: "Noch keine Auszahlungen", copied: "Kopiert!", copyFailed: "Kopieren fehlgeschlagen", joinAndEarn: "Tritt", andEarnMetalTokens: "bei und verdiene Metal-Token!", inviteFriends: "Freunde einladen", earnPerFriendInvite: "Verdiene Metal für jeden eingeladenen Freund", friendsInvited: "Eingeladene Freunde", metalEarned: "Verdientes Metal", metalPerFriend: "Metal pro Freund", commission: "Provision", inviteAFriend: "Freund einladen", linkCopied: "Link kopiert!", copyInviteLink: "Einladungslink kopieren", yourFriends: "Deine Freunde", noFriendsInvitedYet: "Noch keine Freunde eingeladen", shareLinkToStartEarning: "Teile deinen Link und beginne zu verdienen!", user: "Benutzer", joined: "Beigetreten" },
  pt: { walletLoadFailed: "Falha ao carregar dados da carteira", enterUsdtAddress: "Digite seu endereço USDT", enterValidAmount: "Digite um valor válido", minimumWithdrawalIs: "Saque mínimo é", insufficientMetalBalance: "Saldo Metal insuficiente", withdrawalSubmitted: "Solicitação de saque enviada!", withdrawalSubmitFailed: "Falha ao enviar saque", pending: "Pendente", approved: "Aprovado", completed: "Concluído", rejected: "Rejeitado", withdrawMetalTokens: "Saque seus tokens Metal", metalBalance: "Saldo Metal", estimatedProcessing: "Processamento estimado", withdrawToUsdt: "Sacar para USDT", usdtWalletAddress: "Endereço USDT (TRC-20)", enterUsdtAddressShort: "Digite seu endereço USDT", amountMetal: "Valor (Metal)", min: "Mín", withdrawalFeeNotice: "Uma taxa de", willBeDeducted: "será descontada.", requestWithdrawal: "Solicitar saque", withdrawalHistory: "Histórico de saques", noWithdrawalsYet: "Nenhum saque ainda", copied: "Copiado!", copyFailed: "Falha ao copiar", joinAndEarn: "Junte-se ao", andEarnMetalTokens: "e ganhe tokens Metal!", inviteFriends: "Convide amigos", earnPerFriendInvite: "Ganhe Metal por cada amigo convidado", friendsInvited: "Amigos convidados", metalEarned: "Metal ganho", metalPerFriend: "Metal por amigo", commission: "comissão", inviteAFriend: "Convidar um amigo", linkCopied: "Link copiado!", copyInviteLink: "Copiar link de convite", yourFriends: "Seus amigos", noFriendsInvitedYet: "Nenhum amigo convidado ainda", shareLinkToStartEarning: "Compartilhe seu link para começar a ganhar!", user: "Usuário", joined: "Entrou" },
  it: { walletLoadFailed: "Impossibile caricare i dati del wallet", enterUsdtAddress: "Inserisci il tuo indirizzo USDT", enterValidAmount: "Inserisci un importo valido", minimumWithdrawalIs: "Il prelievo minimo è", insufficientMetalBalance: "Saldo Metal insufficiente", withdrawalSubmitted: "Richiesta di prelievo inviata!", withdrawalSubmitFailed: "Invio del prelievo non riuscito", pending: "In attesa", approved: "Approvato", completed: "Completato", rejected: "Rifiutato", withdrawMetalTokens: "Preleva i tuoi token Metal", metalBalance: "Saldo Metal", estimatedProcessing: "Elaborazione stimata", withdrawToUsdt: "Preleva in USDT", usdtWalletAddress: "Indirizzo USDT (TRC-20)", enterUsdtAddressShort: "Inserisci il tuo indirizzo USDT", amountMetal: "Importo (Metal)", min: "Min", withdrawalFeeNotice: "Una commissione di", willBeDeducted: "verrà detratta.", requestWithdrawal: "Richiedi prelievo", withdrawalHistory: "Cronologia prelievi", noWithdrawalsYet: "Nessun prelievo ancora", copied: "Copiato!", copyFailed: "Copia non riuscita", joinAndEarn: "Unisciti a", andEarnMetalTokens: "e guadagna token Metal!", inviteFriends: "Invita amici", earnPerFriendInvite: "Guadagna Metal per ogni amico invitato", friendsInvited: "Amici invitati", metalEarned: "Metal guadagnati", metalPerFriend: "Metal per amico", commission: "commissione", inviteAFriend: "Invita un amico", linkCopied: "Link copiato!", copyInviteLink: "Copia link invito", yourFriends: "I tuoi amici", noFriendsInvitedYet: "Nessun amico invitato", shareLinkToStartEarning: "Condividi il tuo link per iniziare a guadagnare!", user: "Utente", joined: "Iscritto" },
  tr: { walletLoadFailed: "Cüzdan verileri yüklenemedi", enterUsdtAddress: "Lütfen USDT cüzdan adresinizi girin", enterValidAmount: "Lütfen geçerli bir miktar girin", minimumWithdrawalIs: "Minimum çekim", insufficientMetalBalance: "Yetersiz Metal bakiyesi", withdrawalSubmitted: "Çekim talebi gönderildi!", withdrawalSubmitFailed: "Çekim talebi gönderilemedi", pending: "Beklemede", approved: "Onaylandı", completed: "Tamamlandı", rejected: "Reddedildi", withdrawMetalTokens: "Metal tokenlerinizi çekin", metalBalance: "Metal Bakiyesi", estimatedProcessing: "Tahmini İşlem", withdrawToUsdt: "USDT'ye çek", usdtWalletAddress: "USDT Cüzdan Adresi (TRC-20)", enterUsdtAddressShort: "USDT adresinizi girin", amountMetal: "Miktar (Metal)", min: "Min", withdrawalFeeNotice: "Ücret", willBeDeducted: "kesilecektir.", requestWithdrawal: "Çekim Talep Et", withdrawalHistory: "Çekim Geçmişi", noWithdrawalsYet: "Henüz çekim yok", copied: "Kopyalandı!", copyFailed: "Kopyalama başarısız", joinAndEarn: "Katıl", andEarnMetalTokens: "ve Metal token kazan!", inviteFriends: "Arkadaş Davet Et", earnPerFriendInvite: "Her davet edilen arkadaş için Metal kazan", friendsInvited: "Davet edilen arkadaşlar", metalEarned: "Kazanılan Metal", metalPerFriend: "Arkadaş başına Metal", commission: "komisyon", inviteAFriend: "Bir arkadaş davet et", linkCopied: "Bağlantı kopyalandı!", copyInviteLink: "Davet bağlantısını kopyala", yourFriends: "Arkadaşların", noFriendsInvitedYet: "Henüz arkadaş davet edilmedi", shareLinkToStartEarning: "Kazanmaya başlamak için bağlantını paylaş!", user: "Kullanıcı", joined: "Katıldı" },
  ar: { walletLoadFailed: "فشل تحميل بيانات المحفظة", enterUsdtAddress: "يرجى إدخال عنوان محفظة USDT", enterValidAmount: "يرجى إدخال مبلغ صحيح", minimumWithdrawalIs: "الحد الأدنى للسحب هو", insufficientMetalBalance: "رصيد Metal غير كافٍ", withdrawalSubmitted: "تم إرسال طلب السحب!", withdrawalSubmitFailed: "فشل إرسال طلب السحب", pending: "قيد الانتظار", approved: "تمت الموافقة", completed: "مكتمل", rejected: "مرفوض", withdrawMetalTokens: "اسحب رموز Metal الخاصة بك", metalBalance: "رصيد Metal", estimatedProcessing: "وقت المعالجة المتوقع", withdrawToUsdt: "السحب إلى USDT", usdtWalletAddress: "عنوان محفظة USDT ‏(TRC-20)", enterUsdtAddressShort: "أدخل عنوان USDT", amountMetal: "الكمية (Metal)", min: "الحد الأدنى", withdrawalFeeNotice: "سيتم خصم رسوم", willBeDeducted: "من الرصيد.", requestWithdrawal: "طلب سحب", withdrawalHistory: "سجل السحوبات", noWithdrawalsYet: "لا توجد سحوبات بعد", copied: "تم النسخ!", copyFailed: "فشل النسخ", joinAndEarn: "انضم إلى", andEarnMetalTokens: "واكسب رموز Metal!", inviteFriends: "ادعُ الأصدقاء", earnPerFriendInvite: "اكسب Metal مقابل كل صديق تدعوه", friendsInvited: "الأصدقاء المدعوون", metalEarned: "Metal المكتسب", metalPerFriend: "Metal لكل صديق", commission: "عمولة", inviteAFriend: "دعوة صديق", linkCopied: "تم نسخ الرابط!", copyInviteLink: "نسخ رابط الدعوة", yourFriends: "أصدقاؤك", noFriendsInvitedYet: "لم تقم بدعوة أي أصدقاء بعد", shareLinkToStartEarning: "شارك رابطك لبدء الربح!", user: "مستخدم", joined: "انضم" },
  ur: { walletLoadFailed: "والیٹ ڈیٹا لوڈ نہیں ہوا", enterUsdtAddress: "اپنا USDT والیٹ ایڈریس درج کریں", enterValidAmount: "درست رقم درج کریں", minimumWithdrawalIs: "کم از کم نکلوائی", insufficientMetalBalance: "Metal بیلنس ناکافی ہے", withdrawalSubmitted: "نکلوائی کی درخواست جمع ہو گئی!", withdrawalSubmitFailed: "نکلوائی درخواست جمع نہ ہو سکی", pending: "زیر التواء", approved: "منظور", completed: "مکمل", rejected: "مسترد", withdrawMetalTokens: "اپنے Metal ٹوکن نکلوائیں", metalBalance: "Metal بیلنس", estimatedProcessing: "متوقع پراسیسنگ", withdrawToUsdt: "USDT میں نکلوائی", usdtWalletAddress: "USDT والیٹ ایڈریس (TRC-20)", enterUsdtAddressShort: "اپنا USDT ایڈریس درج کریں", amountMetal: "رقم (Metal)", min: "کم از کم", withdrawalFeeNotice: "فیس", willBeDeducted: "منہا کی جائے گی۔", requestWithdrawal: "نکلوائی کی درخواست", withdrawalHistory: "نکلوائی کی تاریخ", noWithdrawalsYet: "ابھی تک کوئی نکلوائی نہیں", copied: "کاپی ہو گیا!", copyFailed: "کاپی ناکام", joinAndEarn: "شامل ہوں", andEarnMetalTokens: "اور Metal ٹوکن کمائیں!", inviteFriends: "دوست مدعو کریں", earnPerFriendInvite: "ہر مدعو دوست پر Metal کمائیں", friendsInvited: "مدعو دوست", metalEarned: "کمائے گئے Metal", metalPerFriend: "فی دوست Metal", commission: "کمیشن", inviteAFriend: "ایک دوست کو مدعو کریں", linkCopied: "لنک کاپی ہو گیا!", copyInviteLink: "دعوتی لنک کاپی کریں", yourFriends: "آپ کے دوست", noFriendsInvitedYet: "ابھی تک کوئی دوست مدعو نہیں کیا", shareLinkToStartEarning: "کمانا شروع کرنے کے لیے اپنا لنک شیئر کریں!", user: "صارف", joined: "شامل ہوا" },
  fa: { walletLoadFailed: "بارگذاری داده‌های کیف پول ناموفق بود", enterUsdtAddress: "لطفاً آدرس کیف پول USDT را وارد کنید", enterValidAmount: "لطفاً مقدار معتبر وارد کنید", minimumWithdrawalIs: "حداقل برداشت", insufficientMetalBalance: "موجودی Metal کافی نیست", withdrawalSubmitted: "درخواست برداشت ارسال شد!", withdrawalSubmitFailed: "ارسال درخواست برداشت ناموفق بود", pending: "در انتظار", approved: "تأیید شد", completed: "تکمیل شد", rejected: "رد شد", withdrawMetalTokens: "برداشت توکن‌های Metal", metalBalance: "موجودی Metal", estimatedProcessing: "زمان پردازش تخمینی", withdrawToUsdt: "برداشت به USDT", usdtWalletAddress: "آدرس کیف پول USDT (TRC-20)", enterUsdtAddressShort: "آدرس USDT خود را وارد کنید", amountMetal: "مقدار (Metal)", min: "حداقل", withdrawalFeeNotice: "کارمزد", willBeDeducted: "کسر خواهد شد.", requestWithdrawal: "درخواست برداشت", withdrawalHistory: "تاریخچه برداشت", noWithdrawalsYet: "هنوز برداشتی انجام نشده", copied: "کپی شد!", copyFailed: "کپی ناموفق بود", joinAndEarn: "به", andEarnMetalTokens: "بپیوندید و توکن Metal کسب کنید!", inviteFriends: "دعوت از دوستان", earnPerFriendInvite: "برای هر دوست دعوت‌شده Metal کسب کنید", friendsInvited: "دوستان دعوت‌شده", metalEarned: "Metal کسب‌شده", metalPerFriend: "Metal برای هر دوست", commission: "کمیسیون", inviteAFriend: "دعوت یک دوست", linkCopied: "لینک کپی شد!", copyInviteLink: "کپی لینک دعوت", yourFriends: "دوستان شما", noFriendsInvitedYet: "هنوز دوستی دعوت نکرده‌اید", shareLinkToStartEarning: "برای شروع کسب درآمد لینک خود را به اشتراک بگذارید!", user: "کاربر", joined: "پیوست" },
  hi: { walletLoadFailed: "वॉलेट डेटा लोड नहीं हो सका", enterUsdtAddress: "कृपया अपना USDT वॉलेट पता दर्ज करें", enterValidAmount: "कृपया सही राशि दर्ज करें", minimumWithdrawalIs: "न्यूनतम निकासी है", insufficientMetalBalance: "Metal बैलेंस अपर्याप्त है", withdrawalSubmitted: "निकासी अनुरोध भेज दिया गया!", withdrawalSubmitFailed: "निकासी अनुरोध भेजने में विफल", pending: "लंबित", approved: "स्वीकृत", completed: "पूर्ण", rejected: "अस्वीकृत", withdrawMetalTokens: "अपने Metal टोकन निकालें", metalBalance: "Metal बैलेंस", estimatedProcessing: "अनुमानित प्रोसेसिंग", withdrawToUsdt: "USDT में निकासी", usdtWalletAddress: "USDT वॉलेट पता (TRC-20)", enterUsdtAddressShort: "अपना USDT पता दर्ज करें", amountMetal: "राशि (Metal)", min: "न्यूनतम", withdrawalFeeNotice: "शुल्क", willBeDeducted: "काटा जाएगा।", requestWithdrawal: "निकासी अनुरोध", withdrawalHistory: "निकासी इतिहास", noWithdrawalsYet: "अभी तक कोई निकासी नहीं", copied: "कॉपी हो गया!", copyFailed: "कॉपी विफल", joinAndEarn: "जुड़ें", andEarnMetalTokens: "और Metal टोकन कमाएँ!", inviteFriends: "दोस्तों को आमंत्रित करें", earnPerFriendInvite: "हर दोस्त के लिए Metal कमाएँ", friendsInvited: "आमंत्रित दोस्त", metalEarned: "कमाया गया Metal", metalPerFriend: "प्रति दोस्त Metal", commission: "कमीशन", inviteAFriend: "एक दोस्त को आमंत्रित करें", linkCopied: "लिंक कॉपी हो गया!", copyInviteLink: "आमंत्रण लिंक कॉपी करें", yourFriends: "आपके दोस्त", noFriendsInvitedYet: "अभी तक कोई दोस्त आमंत्रित नहीं", shareLinkToStartEarning: "कमाई शुरू करने के लिए लिंक साझा करें!", user: "उपयोगकर्ता", joined: "जुड़ा" },
  id: { walletLoadFailed: "Gagal memuat data dompet", enterUsdtAddress: "Masukkan alamat dompet USDT Anda", enterValidAmount: "Masukkan jumlah yang valid", minimumWithdrawalIs: "Penarikan minimum adalah", insufficientMetalBalance: "Saldo Metal tidak cukup", withdrawalSubmitted: "Permintaan penarikan terkirim!", withdrawalSubmitFailed: "Gagal mengirim penarikan", pending: "Menunggu", approved: "Disetujui", completed: "Selesai", rejected: "Ditolak", withdrawMetalTokens: "Tarik token Metal Anda", metalBalance: "Saldo Metal", estimatedProcessing: "Perkiraan proses", withdrawToUsdt: "Tarik ke USDT", usdtWalletAddress: "Alamat Dompet USDT (TRC-20)", enterUsdtAddressShort: "Masukkan alamat USDT Anda", amountMetal: "Jumlah (Metal)", min: "Min", withdrawalFeeNotice: "Biaya", willBeDeducted: "akan dipotong.", requestWithdrawal: "Ajukan Penarikan", withdrawalHistory: "Riwayat Penarikan", noWithdrawalsYet: "Belum ada penarikan", copied: "Tersalin!", copyFailed: "Gagal menyalin", joinAndEarn: "Bergabunglah", andEarnMetalTokens: "dan dapatkan token Metal!", inviteFriends: "Undang Teman", earnPerFriendInvite: "Dapatkan Metal untuk setiap teman yang diundang", friendsInvited: "Teman Diundang", metalEarned: "Metal Diperoleh", metalPerFriend: "Metal per teman", commission: "komisi", inviteAFriend: "Undang Teman", linkCopied: "Tautan tersalin!", copyInviteLink: "Salin tautan undangan", yourFriends: "Teman Anda", noFriendsInvitedYet: "Belum ada teman yang diundang", shareLinkToStartEarning: "Bagikan tautanmu untuk mulai menghasilkan!", user: "Pengguna", joined: "Bergabung" },
  ms: { walletLoadFailed: "Gagal memuat data dompet", enterUsdtAddress: "Sila masukkan alamat dompet USDT anda", enterValidAmount: "Sila masukkan jumlah yang sah", minimumWithdrawalIs: "Pengeluaran minimum ialah", insufficientMetalBalance: "Baki Metal tidak mencukupi", withdrawalSubmitted: "Permintaan pengeluaran dihantar!", withdrawalSubmitFailed: "Gagal menghantar pengeluaran", pending: "Menunggu", approved: "Diluluskan", completed: "Selesai", rejected: "Ditolak", withdrawMetalTokens: "Keluarkan token Metal anda", metalBalance: "Baki Metal", estimatedProcessing: "Pemprosesan anggaran", withdrawToUsdt: "Keluarkan ke USDT", usdtWalletAddress: "Alamat Dompet USDT (TRC-20)", enterUsdtAddressShort: "Masukkan alamat USDT anda", amountMetal: "Jumlah (Metal)", min: "Min", withdrawalFeeNotice: "Yuran", willBeDeducted: "akan ditolak.", requestWithdrawal: "Minta Pengeluaran", withdrawalHistory: "Sejarah Pengeluaran", noWithdrawalsYet: "Belum ada pengeluaran", copied: "Disalin!", copyFailed: "Gagal menyalin", joinAndEarn: "Sertai", andEarnMetalTokens: "dan dapatkan token Metal!", inviteFriends: "Jemput Rakan", earnPerFriendInvite: "Dapat Metal bagi setiap rakan dijemput", friendsInvited: "Rakan Dijemput", metalEarned: "Metal Diperoleh", metalPerFriend: "Metal setiap rakan", commission: "komisen", inviteAFriend: "Jemput rakan", linkCopied: "Pautan disalin!", copyInviteLink: "Salin pautan jemputan", yourFriends: "Rakan anda", noFriendsInvitedYet: "Belum ada rakan dijemput", shareLinkToStartEarning: "Kongsi pautan anda untuk mula menjana!", user: "Pengguna", joined: "Menyertai" },
  bn: { walletLoadFailed: "ওয়ালেট ডেটা লোড করা যায়নি", enterUsdtAddress: "আপনার USDT ওয়ালেট ঠিকানা লিখুন", enterValidAmount: "সঠিক পরিমাণ লিখুন", minimumWithdrawalIs: "ন্যূনতম উত্তোলন", insufficientMetalBalance: "Metal ব্যালান্স অপর্যাপ্ত", withdrawalSubmitted: "উত্তোলন অনুরোধ জমা হয়েছে!", withdrawalSubmitFailed: "উত্তোলন অনুরোধ ব্যর্থ", pending: "অপেক্ষমাণ", approved: "অনুমোদিত", completed: "সম্পন্ন", rejected: "প্রত্যাখ্যাত", withdrawMetalTokens: "আপনার Metal টোকেন উত্তোলন করুন", metalBalance: "Metal ব্যালান্স", estimatedProcessing: "আনুমানিক প্রসেসিং", withdrawToUsdt: "USDT-তে উত্তোলন", usdtWalletAddress: "USDT ওয়ালেট ঠিকানা (TRC-20)", enterUsdtAddressShort: "আপনার USDT ঠিকানা লিখুন", amountMetal: "পরিমাণ (Metal)", min: "সর্বনিম্ন", withdrawalFeeNotice: "ফি", willBeDeducted: "কাটা হবে।", requestWithdrawal: "উত্তোলন অনুরোধ", withdrawalHistory: "উত্তোলনের ইতিহাস", noWithdrawalsYet: "এখনও কোনো উত্তোলন নেই", copied: "কপি হয়েছে!", copyFailed: "কপি ব্যর্থ", joinAndEarn: "যোগ দিন", andEarnMetalTokens: "এবং Metal টোকেন আয় করুন!", inviteFriends: "বন্ধু আমন্ত্রণ", earnPerFriendInvite: "প্রতি বন্ধুর জন্য Metal আয় করুন", friendsInvited: "আমন্ত্রিত বন্ধু", metalEarned: "আয়কৃত Metal", metalPerFriend: "প্রতি বন্ধু Metal", commission: "কমিশন", inviteAFriend: "একজন বন্ধুকে আমন্ত্রণ করুন", linkCopied: "লিংক কপি হয়েছে!", copyInviteLink: "আমন্ত্রণ লিংক কপি করুন", yourFriends: "আপনার বন্ধুরা", noFriendsInvitedYet: "এখনও কোনো বন্ধু আমন্ত্রণ করা হয়নি", shareLinkToStartEarning: "আয় শুরু করতে আপনার লিংক শেয়ার করুন!", user: "ব্যবহারকারী", joined: "যোগ দিয়েছে" },
  vi: { walletLoadFailed: "Không tải được dữ liệu ví", enterUsdtAddress: "Vui lòng nhập địa chỉ ví USDT", enterValidAmount: "Vui lòng nhập số tiền hợp lệ", minimumWithdrawalIs: "Rút tối thiểu là", insufficientMetalBalance: "Số dư Metal không đủ", withdrawalSubmitted: "Đã gửi yêu cầu rút!", withdrawalSubmitFailed: "Gửi yêu cầu rút thất bại", pending: "Đang chờ", approved: "Đã duyệt", completed: "Hoàn tất", rejected: "Bị từ chối", withdrawMetalTokens: "Rút token Metal của bạn", metalBalance: "Số dư Metal", estimatedProcessing: "Thời gian xử lý ước tính", withdrawToUsdt: "Rút sang USDT", usdtWalletAddress: "Địa chỉ ví USDT (TRC-20)", enterUsdtAddressShort: "Nhập địa chỉ USDT của bạn", amountMetal: "Số lượng (Metal)", min: "Tối thiểu", withdrawalFeeNotice: "Phí", willBeDeducted: "sẽ được trừ.", requestWithdrawal: "Yêu cầu rút", withdrawalHistory: "Lịch sử rút tiền", noWithdrawalsYet: "Chưa có lần rút nào", copied: "Đã sao chép!", copyFailed: "Sao chép thất bại", joinAndEarn: "Tham gia", andEarnMetalTokens: "và kiếm token Metal!", inviteFriends: "Mời bạn bè", earnPerFriendInvite: "Kiếm Metal cho mỗi bạn bè được mời", friendsInvited: "Bạn bè đã mời", metalEarned: "Metal đã kiếm", metalPerFriend: "Metal mỗi bạn", commission: "hoa hồng", inviteAFriend: "Mời một người bạn", linkCopied: "Đã sao chép liên kết!", copyInviteLink: "Sao chép liên kết mời", yourFriends: "Bạn bè của bạn", noFriendsInvitedYet: "Bạn chưa mời bạn bè nào", shareLinkToStartEarning: "Chia sẻ liên kết để bắt đầu kiếm!", user: "Người dùng", joined: "Tham gia" },
  pcm: { walletLoadFailed: "No fit load wallet data", enterUsdtAddress: "Abeg put your USDT wallet address", enterValidAmount: "Abeg put correct amount", minimumWithdrawalIs: "Minimum withdrawal na", insufficientMetalBalance: "Metal balance no reach", withdrawalSubmitted: "Withdrawal request don submit!", withdrawalSubmitFailed: "Withdrawal request no submit", pending: "Pending", approved: "Approved", completed: "Completed", rejected: "Rejected", withdrawMetalTokens: "Withdraw your Metal tokens", metalBalance: "Metal Balance", estimatedProcessing: "Estimated Processing", withdrawToUsdt: "Withdraw to USDT", usdtWalletAddress: "USDT Wallet Address (TRC-20)", enterUsdtAddressShort: "Put your USDT address", amountMetal: "Amount (Metal)", min: "Min", withdrawalFeeNotice: "Fee of", willBeDeducted: "go deduct.", requestWithdrawal: "Request Withdrawal", withdrawalHistory: "Withdrawal History", noWithdrawalsYet: "No withdrawals yet", copied: "Copied!", copyFailed: "Copy fail", joinAndEarn: "Join", andEarnMetalTokens: "and earn Metal tokens!", inviteFriends: "Invite Friends", earnPerFriendInvite: "Earn Metal for every friend wey you invite", friendsInvited: "Friends Invited", metalEarned: "Metal Earned", metalPerFriend: "Metal per friend", commission: "commission", inviteAFriend: "Invite a Friend", linkCopied: "Link Copied!", copyInviteLink: "Copy Invite Link", yourFriends: "Your Friends", noFriendsInvitedYet: "You never invite any friend yet", shareLinkToStartEarning: "Share your link make you start earn!", user: "User", joined: "Joined" },
}

const commonUiLabels: Partial<Record<AppLanguage, Dict>> = {
  en: { show: "Show", showLess: "Show less", gameTutorialDescShort: "Learn controls" },
  zh: { show: "显示", showLess: "收起", gameTutorialDescShort: "学习操作" },
  ja: { show: "表示", showLess: "閉じる", gameTutorialDescShort: "操作を学ぶ" },
  ru: { show: "Показать", showLess: "Скрыть", gameTutorialDescShort: "Изучить управление" },
  fr: { show: "Afficher", showLess: "Afficher moins", gameTutorialDescShort: "Apprendre les commandes" },
  pt: { show: "Mostrar", showLess: "Mostrar menos", gameTutorialDescShort: "Aprender controles" },
  es: { show: "Mostrar", showLess: "Mostrar menos", gameTutorialDescShort: "Aprender controles" },
  de: { show: "Anzeigen", showLess: "Weniger anzeigen", gameTutorialDescShort: "Steuerung lernen" },
  tr: { show: "Göster", showLess: "Daha az göster", gameTutorialDescShort: "Kontrolleri öğren" },
  ar: { show: "عرض", showLess: "عرض أقل", gameTutorialDescShort: "تعلّم التحكم" },
  ur: { show: "دکھائیں", showLess: "کم دکھائیں", gameTutorialDescShort: "کنٹرول سیکھیں" },
  pcm: { show: "Show", showLess: "Show less", gameTutorialDescShort: "Learn controls" },
  hi: { show: "दिखाएँ", showLess: "कम दिखाएँ", gameTutorialDescShort: "कंट्रोल सीखें" },
  id: { show: "Tampilkan", showLess: "Tampilkan lebih sedikit", gameTutorialDescShort: "Pelajari kontrol" },
  ms: { show: "Tunjuk", showLess: "Tunjuk kurang", gameTutorialDescShort: "Belajar kawalan" },
  bn: { show: "দেখান", showLess: "কম দেখান", gameTutorialDescShort: "কন্ট্রোল শিখুন" },
  vi: { show: "Hiển thị", showLess: "Thu gọn", gameTutorialDescShort: "Học điều khiển" },
  fa: { show: "نمایش", showLess: "نمایش کمتر", gameTutorialDescShort: "کنترل‌ها را یاد بگیرید" },
  ko: { show: "보기", showLess: "접기", gameTutorialDescShort: "조작 배우기" },
  it: { show: "Mostra", showLess: "Mostra meno", gameTutorialDescShort: "Impara i comandi" },
}

type Ctx = {
  language: AppLanguage
  setLanguage: (lang: AppLanguage) => void
  t: (key: string, fallback?: string) => string
}

const LanguageContext = createContext<Ctx | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>("en")

  useEffect(() => {
    setLanguageState("en")
  }, [])

  const applyLanguageToGame = (lang: AppLanguage) => {
    try {
      const iframe = document.getElementById("metal-game-iframe") as HTMLIFrameElement | null
      const win = iframe?.contentWindow as any
      try { localStorage.setItem("appLanguage", lang) } catch {}
      if (!win) return
      if (typeof win.Metal8ball_setLanguage === "function") win.Metal8ball_setLanguage(lang)
      else if (win?.Metal8ball?.localStorage?.setItem) win.Metal8ball.localStorage.setItem("appLanguage", lang)
    } catch {}
  }

  const setLanguage = (_lang: AppLanguage) => {
    setLanguageState("en")
    applyLanguageToGame("en")
  }

  useEffect(() => {
    document.documentElement.lang = "en"
    applyLanguageToGame("en")
  }, [])

  const t = (key: string, fallback?: string) => {
    return (
      commonUiLabels[language]?.[key] ||
      pageDictionaries[language]?.[key] ||
      dictionaries[language]?.[key] ||
      commonUiLabels.en?.[key] ||
      pageDictionaries.en?.[key] ||
      dictionaries.en[key] ||
      fallback ||
      key
    )
  }

  const value = useMemo(() => ({ language, setLanguage, t }), [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider")
  return ctx
}
